name: expensy
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  table_calendar: ^3.0.8
  syncfusion_flutter_charts: ^20.4.49
  intl: ^0.18.0
  flutter_svg: ^2.0.0 # Added dependency for SVG support
  supabase_flutter: ^2.8.2
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/images/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/svgImgs/ # Added assets folder for SVG images
